name: sambhav_polaris
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  chucker_flutter: ^1.7.2
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/app/generated
