name: sambhav_polaris
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  cached_network_image: ^3.3.1
  dio: ^5.4.3+1
  chucker_flutter: ^1.7.2
  flutter_bloc: ^8.1.6
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  either_dart: ^1.0.0
  internet_connection_checker_plus: ^2.4.2
  get_storage: ^2.1.1
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  aws_s3_upload_lite: ^0.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.11
  flutter_lints: ^3.0.0
  flutter_gen_runner: ^5.5.0+1
  json_serializable: ^6.8.0
  freezed: ^2.5.2

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_gen:
  output: lib/app/generated
